# mkdocs.yml
site_name: "AKK - Portfolio & Digital Garden"
site_url: https://akashk.dev/
dev_addr: "127.0.0.1:9000"
theme:
  name: shadcn
  show_title: true
  show_stargazers: false
  pygments_style:
    light: dracula
    dark: dracula
  icon: lucide:rocket
  topbar_sections: false
  katex_options:
    macros:
      "\\RR": "\\mathbb{R}"
      "\\dx": "\\mathrm{d}x"
  show_datetime: false
  icon: /img/favicon.ico
markdown_extensions:
  - pymdownx.fancylists:
      inject_style: true
  - pymdownx.saneheaders
  - shadcn.extensions.iconify
  - pymdownx.escapeall:
      hardbreak: true
  - admonition
  - pymdownx.fancylists
  - pymdownx.saneheaders
  - pymdownx.progressbar
  - pymdownx.tilde
  - pymdownx.highlight:
      pygments_style: dracula
      css_class: codehilite
      noclasses: false
      guess_lang: false
      use_pygments: true
  - pymdownx.superfences
  - shadcn.extensions.codexec
  - pymdownx.arithmatex:
      generic: true
plugins:
  - shadcn/nav-to-json
  - shadcn/search
